### ISSUE TITLE
Missing posgresql python binding

### ISSUE THREAD

**Issue by Sherpard** [mastermindg/trac-docker-ubuntu#2]
When trying to setup an environment that relies on posgres, trac lacks the connector.

psycopg should be installed at the dockerfile to support posgres.

PS: Amazing work!

**Comment by mastermindg** [comment]
Thanks for the heads up. I've added the postgres python bindings. Let me know if this works for you.

**Comment by Sherpard** [comment]
It works as expected :) thank you @mastermindg
